# Generated by Django 3.1.2 on 2020-11-20 18:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
                ('name', models.CharField(default='', max_length=200)),
                ('kt', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Контрольная точка №1', max_length=30)),
                ('rating', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botbi20i1.laboratory')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(default='', max_length=20)),
                ('name', models.CharField(default='', max_length=60)),
                ('rating', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('labs', models.ManyToManyField(through='botbi20i1.Stats', to='botbi20i1.Laboratory')),
            ],
        ),
        migrations.AddField(
            model_name='stats',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botbi20i1.student'),
        ),
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('lab', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='botbi20i1.laboratory')),
            ],
        ),
    ]
