# Generated by Django 3.1.2 on 2020-11-28 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botbi20i1', '0002_auto_20201121_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='git_hub',
            field=models.CharField(default='', max_length=100),
        ),
    ]
