# Generated by Django 3.1.2 on 2020-12-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botbi20i1', '0003_student_git_hub'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='personal_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
