# Generated by Django 3.1.2 on 2020-12-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botbi20i1', '0010_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='groups',
            new_name='course',
        ),
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
