# Generated by Django 3.1.2 on 2020-12-08 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botbi20i1', '0011_auto_20201206_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='group_id',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='botbi20i1.group'),
        ),
    ]
