# Generated by Django 3.1.2 on 2020-12-15 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botbi20i1', '0012_student_group_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
    ]
