# Generated by Django 3.1.2 on 2020-12-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botbi20i1', '0014_auto_20201220_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='code',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
