# Generated by Django 3.1.2 on 2020-12-25 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botbi20i1', '0015_laboratory_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='group_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='botbi20i1.group'),
        ),
    ]
