# Generated by Django 3.1.2 on 2020-12-26 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botbi20i1', '0017_auto_20201226_0327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratory',
            name='code',
        ),
        migrations.AlterField(
            model_name='student',
            name='group_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='botbi20i1.group'),
        ),
    ]
