# Generated by Django 3.1.2 on 2020-12-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botbi20i1', '0018_auto_20201226_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratory',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='kt',
            field=models.PositiveIntegerField(default=1, verbose_name='КТ'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Название'),
        ),
    ]
