# Generated by Django 3.1.2 on 2021-01-06 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('botbi20i1', '0022_auto_20210106_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='login',
            field=models.ForeignKey(default='student', max_length=50, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
