# Generated by Django 3.1.2 on 2021-01-10 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botbi20i1', '0033_auto_20210110_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
