# Generated by Django 3.1.2 on 2021-01-16 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botbi20i1', '0035_student_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FilePathField(default=None)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botbi20i1.laboratory')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botbi20i1.student')),
            ],
        ),
    ]
