# Generated by Django 3.1.2 on 2021-01-16 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botbi20i1', '0038_auto_20210116_1617'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Files',
            new_name='File',
        ),
    ]
