# Generated by Django 3.1.2 on 2021-01-17 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botbi20i1', '0039_auto_20210116_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='lab',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='botbi20i1.laboratory'),
        ),
        migrations.AlterField(
            model_name='file',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='botbi20i1.student'),
        ),
    ]
