# Generated by Django 3.1.2 on 2021-01-17 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botbi20i1', '0040_auto_20210117_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botbi20i1.laboratory'),
        ),
    ]
