# Generated by Django 3.1.2 on 2021-02-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botbi20i1', '0042_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='student',
        ),
        migrations.AddField(
            model_name='file',
            name='student',
            field=models.ManyToManyField(to='botbi20i1.Student'),
        ),
    ]
