# Generated by Django 3.1.2 on 2021-02-04 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botbi20i1', '0043_auto_20210204_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='student',
        ),
        migrations.AddField(
            model_name='file',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='botbi20i1.student'),
            preserve_default=False,
        ),
    ]
