# Generated by Django 3.1.2 on 2021-02-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botbi20i1', '0045_auto_20210205_0146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='lab',
        ),
        migrations.AddField(
            model_name='file',
            name='lab',
            field=models.ManyToManyField(to='botbi20i1.Laboratory'),
        ),
    ]
