# Generated by Django 3.1.2 on 2021-02-04 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botbi20i1', '0046_auto_20210205_0152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='lab',
        ),
        migrations.AddField(
            model_name='file',
            name='lab',
            field=models.ForeignKey(default=65, on_delete=django.db.models.deletion.CASCADE, to='botbi20i1.laboratory'),
            preserve_default=False,
        ),
    ]
