# Generated by Django 3.1.2 on 2021-02-04 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botbi20i1', '0047_auto_20210205_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='lab',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='botbi20i1.laboratory'),
        ),
    ]
