# Generated by Django 3.1.2 on 2021-02-09 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botbi20i1', '0050_auto_20210205_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='group',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='botbi20i1.group'),
            preserve_default=False,
        ),
    ]
