# Generated by Django 3.1.2 on 2021-02-09 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botbi20i1', '0051_stats_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stats',
            name='group',
        ),
    ]
