# Generated by Django 3.1.2 on 2021-02-11 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botbi20i1', '0053_laboratory_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='group_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='botbi20i1.group'),
        ),
    ]
