# Generated by Django 3.1.2 on 2021-02-11 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botbi20i1', '0054_stats_group_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stats',
            name='group_id',
        ),
    ]
