# Generated by Django 3.1.6 on 2021-02-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botbi20i1', '0055_remove_stats_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='patronymic',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.CharField(default='', max_length=50),
        ),
    ]
