# Generated by Django 3.1.6 on 2021-02-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botbi20i1', '0056_auto_20210225_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='additional_Information',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
    ]
