# Generated by Django 3.1.7 on 2021-03-15 17:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botbi20i1', '0058_auto_20210226_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='weight',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Вес лабы (%)'),
        ),
    ]
