# Generated by Django 3.1.7 on 2021-03-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botbi20i1', '0060_educationcontrol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationcontrol',
            name='number',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3)], default=1),
        ),
    ]
