# Generated by Django 3.1.7 on 2021-03-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botbi20i1', '0061_auto_20210317_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationcontrol',
            name='number',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3)], default='1'),
        ),
    ]
