# Generated by Django 3.1.7 on 2021-03-17 16:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botbi20i1', '0062_auto_20210317_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationcontrol',
            name='group',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='botbi20i1.group'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='educationcontrol',
            name='number',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default='1', verbose_name='Номер КТ'),
        ),
        migrations.AlterField(
            model_name='educationcontrol',
            name='weight',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Вес КТ (%)'),
        ),
    ]
