# Generated by Django 3.1.7 on 2021-03-17 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botbi20i1', '0063_auto_20210317_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='botbi20i1.teacher'),
        ),
        migrations.AlterField(
            model_name='educationcontrol',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='botbi20i1.group', verbose_name='Группа'),
        ),
    ]
