# Generated by Django 3.1.7 on 2021-03-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botbi20i1', '0064_auto_20210317_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий преподователя'),
        ),
    ]
