# Generated by Django 3.1.7 on 2021-05-28 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botbi20i1', '0066_student_student_dir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_dir',
        ),
    ]
