# Generated by Django 3.1.7 on 2021-05-28 17:55

import botbi20i1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botbi20i1', '0068_student_student_dir'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='file_input',
            field=models.FileField(blank=True, default=None, upload_to=botbi20i1.models.folder_path_fileIn),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='file_output',
            field=models.FileField(blank=True, default=None, upload_to=botbi20i1.models.folder_path_fileOut),
        ),
    ]
