# Generated by Django 3.1.7 on 2021-05-30 21:27

import botbi20i1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botbi20i1', '0069_auto_20210528_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(default=None, upload_to=botbi20i1.models.folder_path_students_file),
        ),
    ]
