# Generated by Django 3.1.6 on 2021-03-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=1250, verbose_name='Текст')),
                ('photo', models.FileField(blank=True, upload_to='', verbose_name='Фото')),
                ('File', models.FileField(blank=True, upload_to='', verbose_name='Файл')),
                ('Date', models.DateField(auto_now=True)),
            ],
        ),
    ]
