# Generated by Django 3.1.6 on 2021-03-07 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boTtelegramm', '0003_auto_20210307_0231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название группы')),
                ('group', models.CharField(max_length=50, verbose_name='Группа')),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='File',
            field=models.CharField(blank=True, max_length=50, verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.CharField(blank=True, max_length=250, verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='news',
            name='group',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='boTtelegramm.group'),
        ),
    ]
