# Generated by Django 3.1.6 on 2021-03-07 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boTtelegramm', '0004_auto_20210307_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='group',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='boTtelegramm.group'),
        ),
    ]
